### ISSUE TITLE
tslint errors from @types fail builds

### ISSUE THREAD

**Issue by taras** [DxCx/ts-library-starter#5]
<img width="855" alt="screen shot 2017-08-14 at 4 11 58 pm" src="https://user-images.githubusercontent.com/74687/29268645-576bce9e-810b-11e7-97c5-12533fe71f51.png">

**Comment by taras** [comment]
This is in master. What are these errors?

**Comment by DxCx** [comment]
This is very old typescript with very old webpack
I would suggest to update them both.
Im on vacation without laptop but i dont mind doing it myself next week
when im back

**Comment by happysalada** [comment]
just tried updating all the packages, unfortunately it doesn't work.
in the tsconfig, setting
`"noImplicitAny": false,`
will get rid of 3 of the errors, however there are still 3 errors on some types being expected

**Comment by DxCx** [comment]
@happysalada i meant that we should start with upgrading as everything is just old.
anyway, i've done what's needed to support latest packages.
will be merged to master soon, enjoy =)
